targets:
  $default:
    builders:
      dart_json_mapper:
        options:
          iterables: List, Set, HashSet, UnmodifiableListView
        generate_for:
          - test/provider_templet_test.dart
